"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

This settings module loads environment variables to configure the Stafflink
integration with the IAM service.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(value: str | None) -> List[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-v*()3-_akcjt1i82)m!n4!g!&ggxvl3jlw8oa)+bfc05%dxm^5",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool(os.environ.get("DEBUG"), default=True)

ALLOWED_HOSTS = _env_list(os.environ.get("ALLOWED_HOSTS"))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",      # DRF
    "corsheaders",         # CORS
    "api",                 # tu app recién creada
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",  # debe ir antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# REST Framework base configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
_cors_from_env = _env_list(os.environ.get("CORS_ALLOWED_ORIGINS"))
if _cors_from_env:
    CORS_ALLOWED_ORIGINS = _cors_from_env
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_CREDENTIALS = True

# IAM integration
IAM_BASE_URL = os.environ.get("IAM_BASE_URL", "http://localhost:58000/api/v1").rstrip("/")
IAM_APP_ID = os.environ.get(
    "IAM_APP_ID",
    "00000000-0000-0000-0000-000000000000",
)
IAM_TIMEOUT_SECONDS = float(os.environ.get("IAM_TIMEOUT_SECONDS", "10"))
IAM_CAPTCHA_REQUIRED = _env_bool(os.environ.get("IAM_CAPTCHA_REQUIRED"), default=False)

# Token / cookie configuration
STAFFLINK_ACCESS_TOKEN_COOKIE_NAME = os.environ.get(
    "STAFFLINK_ACCESS_TOKEN_COOKIE_NAME",
    "stafflink_access_token",
)
STAFFLINK_ACCESS_TOKEN_COOKIE_SECURE = _env_bool(
    os.environ.get("STAFFLINK_ACCESS_TOKEN_COOKIE_SECURE"),
    default=not DEBUG,
)
STAFFLINK_ACCESS_TOKEN_COOKIE_SAMESITE = os.environ.get(
    "STAFFLINK_ACCESS_TOKEN_COOKIE_SAMESITE",
    "Lax",
)
STAFFLINK_ACCESS_TOKEN_COOKIE_PATH = "/"
