"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

This settings module loads environment variables to configure the Stafflink
integration with the IAM service.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, List

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(value: str | None) -> List[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-v*()3-_akcjt1i82)m!n4!g!&ggxvl3jlw8oa)+bfc05%dxm^5",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool(os.environ.get("DEBUG"), default=True)

ALLOWED_HOSTS = _env_list(os.environ.get("ALLOWED_HOSTS"))


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # DRF
    "corsheaders",  # CORS
    "drf_spectacular",  # OpenAPI/Swagger
    "api",  # app raíz existente
    "api.v1.recruitment",  # dominio de reclutamiento (ONE-PASS)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # debe ir antes de CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "stafflink"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# REST Framework base configuration
REST_FRAMEWORK: dict[str, Any] = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.auth.authentication.IAMCookieAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "UNAUTHENTICATED_USER": None,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Stafflink API",
    "DESCRIPTION": "API v1 para el flujo de reclutamiento ONE-PASS",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
_cors_from_env = _env_list(os.environ.get("CORS_ALLOWED_ORIGINS"))
if _cors_from_env:
    CORS_ALLOWED_ORIGINS = _cors_from_env
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_CREDENTIALS = True

# IAM integration
IAM_BASE_URL = os.environ.get("IAM_BASE_URL", "http://localhost:58000/api/v1").rstrip(
    "/"
)
IAM_APP_ID = os.environ.get(
    "IAM_APP_ID",
    "00000000-0000-0000-0000-000000000000",
)
IAM_CONTROL_APP_ID = os.environ.get(
    "IAM_CONTROL_APP_ID",
    "ed9ca85c-8247-4043-9fd2-d1c47497f461",
)
IAM_TIMEOUT_SECONDS = float(os.environ.get("IAM_TIMEOUT_SECONDS", "10"))
IAM_CAPTCHA_REQUIRED = _env_bool(os.environ.get("IAM_CAPTCHA_REQUIRED"), default=False)
IAM_SERVICE_TOKEN = os.environ.get("IAM_SERVICE_TOKEN")  # opcional, para consultar Directory
IAM_SERVICE_USER = os.environ.get("IAM_SERVICE_USER")
IAM_SERVICE_PASSWORD = os.environ.get("IAM_SERVICE_PASSWORD")

# Token / cookie configuration
STAFFLINK_ACCESS_TOKEN_COOKIE_NAME = os.environ.get(
    "STAFFLINK_ACCESS_TOKEN_COOKIE_NAME",
    "stafflink_access_token",
)
STAFFLINK_ACCESS_TOKEN_COOKIE_SECURE = _env_bool(
    os.environ.get("STAFFLINK_ACCESS_TOKEN_COOKIE_SECURE"),
    default=not DEBUG,
)
STAFFLINK_ACCESS_TOKEN_COOKIE_SAMESITE = os.environ.get(
    "STAFFLINK_ACCESS_TOKEN_COOKIE_SAMESITE",
    "Lax",
)
STAFFLINK_ACCESS_TOKEN_COOKIE_PATH = "/"

# Upload / storage configuration
STAFFLINK_STORAGE_BACKEND = os.environ.get("STAFFLINK_STORAGE_BACKEND", "local").lower()
STAFFLINK_STORAGE_BASE_PATH = os.environ.get(
    "STAFFLINK_STORAGE_BASE_PATH",
    str(BASE_DIR / "var" / "uploads"),
)
STAFFLINK_UPLOAD_MAX_SIZE_BYTES = int(
    os.environ.get("STAFFLINK_UPLOAD_MAX_SIZE_BYTES", str(5 * 1024 * 1024))
)
STAFFLINK_ALLOWED_UPLOAD_EXTENSIONS = _env_list(
    os.environ.get("STAFFLINK_ALLOWED_UPLOAD_EXTENSIONS")
) or [
    "jpg",
    "jpeg",
    "png",
    "pdf",
]

STAFFLINK_EXPORT_OUTPUT_DIR = os.environ.get(
    "STAFFLINK_EXPORT_OUTPUT_DIR", str(BASE_DIR / "var" / "exports")
)
