# Generated by Django 5.2.8 on 2025-11-12 03:55

from __future__ import annotations

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("second_last_name", models.CharField(blank=True, max_length=150)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("dni", "DNI"), ("ce", "Carné de extranjería")],
                        max_length=10,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Za-z]{4,16}$", "Formato inválido"
                            )
                        ],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("alternate_phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Enviado"),
                            ("under_review", "En revisión"),
                            ("verified_ok", "Verificado"),
                            ("observed", "Observado"),
                            ("rejected", "Rechazado"),
                            ("exported", "Exportado"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("lpdp_consent", models.BooleanField(default=False)),
                ("lpdp_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("origin_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SmartExportBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_code", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("generated", "Generado"),
                            ("delivered", "Entregado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generated_by", models.UUIDField(blank=True, null=True)),
                ("generated_by_name", models.CharField(blank=True, max_length=255)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("file_checksum", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicantDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dni_front", "DNI anverso"),
                            ("dni_back", "DNI reverso"),
                            ("ce_front", "CE anverso"),
                            ("ce_back", "CE reverso"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=512)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size_bytes", models.PositiveIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("uploaded_by", models.UUIDField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="recruitment.applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaña"),
                            ("link", "Link"),
                            ("applicant", "Postulante"),
                            ("verification", "Verificación"),
                            ("export", "Exportación"),
                            ("other", "Otros"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("action", models.CharField(max_length=64)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="recruitment_entity__8faada_idx",
                    ),
                    models.Index(
                        fields=["actor_id"], name="recruitment_actor_i_68f685_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador público del link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "owner_id",
                    models.UUIDField(help_text="UUID del usuario IAM reclutador"),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("expired", "Vencida"),
                            ("revoked", "Anulada"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("onsite", "Presencial"),
                            ("hybrid", "Híbrido"),
                            ("remote", "Remoto"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                (
                    "employment_condition",
                    models.CharField(
                        choices=[("payroll", "Planilla"), ("contractor", "Honorarios")],
                        default="payroll",
                        max_length=20,
                    ),
                ),
                ("period_label", models.CharField(blank=True, max_length=120)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "rest_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Lunes"),
                            ("tuesday", "Martes"),
                            ("wednesday", "Miércoles"),
                            ("thursday", "Jueves"),
                            ("friday", "Viernes"),
                            ("saturday", "Sábado"),
                            ("sunday", "Domingo"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "work_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                ("quota", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha/hora límite del link (America/Lima)"
                    ),
                ),
                ("expires_automatically", models.BooleanField(default=True)),
                (
                    "qr_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencia al código QR almacenado en el frontend/perimeter",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="recruitment.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicants",
                to="recruitment.recruitmentlink",
            ),
        ),
        migrations.CreateModel(
            name="SmartExportBatchItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("exported", "Exportado"),
                            ("failed", "Fallido"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_items",
                        to="recruitment.applicant",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recruitment.smartexportbatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="smartexportbatch",
            name="applicants",
            field=models.ManyToManyField(
                related_name="export_batches",
                through="recruitment.SmartExportBatchItem",
                to="recruitment.applicant",
            ),
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Apto"),
                            ("observed", "Observado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_by_name", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("requested_correction_by", models.UUIDField(blank=True, null=True)),
                (
                    "requested_correction_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "risk_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resultados de deduplicación/blacklist",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="recruitment.applicant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recruitmentlink",
            index=models.Index(
                fields=["status", "expires_at"], name="recruitment_status_6295fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicant",
            constraint=models.UniqueConstraint(
                fields=("document_type", "document_number", "link"),
                name="unique_document_per_link",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="smartexportbatchitem",
            unique_together={("batch", "applicant")},
        ),
    ]
