# Generated by Django 5.2.8 on 2025-11-12 05:43

from __future__ import annotations

from django.db import migrations, models

import api.v1.recruitment.models


class Migration(migrations.Migration):

    dependencies: list[tuple[str, str]] = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="alternate_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="metadata",
            field=models.JSONField(
                blank=True, default=api.v1.recruitment.models._empty_dict
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="second_last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="applicantdocument",
            name="checksum",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="site_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentlink",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recruitmentlink",
            name="owner_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentlink",
            name="period_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="recruitmentlink",
            name="qr_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Referencia al código QR almacenado en el frontend/perimeter",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="recruitmentlink",
            name="rest_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Lunes"),
                    ("tuesday", "Martes"),
                    ("wednesday", "Miércoles"),
                    ("thursday", "Jueves"),
                    ("friday", "Viernes"),
                    ("saturday", "Sábado"),
                    ("sunday", "Domingo"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="decision_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="verification",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="verification",
            name="reviewed_by_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="verification",
            name="risk_flags",
            field=models.JSONField(
                blank=True,
                default=api.v1.recruitment.models._empty_dict,
                help_text="Resultados de deduplicación/blacklist",
            ),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(
                fields=["status", "-submitted_at"], name="recruitment_status_d35d02_idx"
            ),
        ),
    ]
